name: Java CI

on:
  push:
    branches:
      - main                # Run CI on pushes to the 'main' branch
  pull_request:
    branches:
      - main                # Run CI on pull requests to the 'main' branch
  workflow_dispatch:        # Allows manual triggering of the workflow

jobs:
  build:
    runs-on: ubuntu-latest  # Use the latest Ubuntu runner

    steps:
      # Step 1: Checkout the code
      - name: Checkout code
        uses: actions/checkout@v3

      # Step 2: Set up JDK
      - name: Set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin' # JDK distribution (temurin, zulu, adopt)
          java-version: '11'       # Specify the Java version

      # Step 3: Cache Maven dependencies for faster builds
      - name: Cache Maven packages
        uses: actions/cache@v3
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-

      # Step 4: Build the project using Maven
      - name: Build with Maven
        run: mvn clean install

      # Step 5: Run tests using Maven
      - name: Run tests
        run: mvn test

      # Optional: Generate a test coverage report using JaCoCo (for Maven)
      - name: Code Coverage
        run: mvn jacoco:report

      # Optional: Upload test results as artifacts
      - name: Upload test results
        uses: actions/upload-artifact@v3
        with:
          name: test-results
          path: target/surefire-reports/

